# Streamlit secrets file
# Find your API key at https://platform.openai.com/api-keys

# OpenAI API Key (required)
openai_api_key = "YOUR_OPENAI_API_KEY_HERE"

# You can add other API keys or configuration here
# serp_api_key = "YOUR_SERP_API_KEY"
